[package]
name = "SimpleDB"
version = "0.1.0"
edition = "2021"

[dependencies]
ractor = "0.14.2"
tokio = {version = "1.41.1", features = ["rt-multi-thread"]}
log = "0.4.22"
simplelog = "^0.12.0"
redis-protocol = { version = "6.0.0", features = ["bytes"] }
redis-protocol-bridge = { git = "https://github.com/NilsDeckert/redis-protocol-bridge"}
